const assert = require('node:assert/strict');
const Engine = require('../app/src/main/assets/engine.js');

const game = new Engine(() => .5);
assert.equal(game.mode, 'ready');
game.reset();
game.move(-1000);
for (let i = 0; i < 40; i++) game.tick(.02);
assert.equal(game.x, 25, 'ship stays inside left edge');
game.move(1000);
for (let i = 0; i < 40; i++) game.tick(.02);
assert.equal(game.x, 335, 'ship stays inside right edge');
assert.ok(game.obstacles.length > 0, 'obstacles spawn during gameplay');
assert.ok(game.score > 0, 'survival earns points');
game.pause();
const snapshot = JSON.stringify(game);
game.tick(.04);
assert.equal(JSON.stringify(game), snapshot, 'pause freezes all gameplay');
game.resume();
assert.equal(game.mode, 'playing');
game.reset();
assert.equal(game.score, 0);
assert.equal(game.obstacles.length, 0);
game.obstacles.push({x:game.x, y:game.y-80, radius:18, speed:4000, angle:0, spin:0});
game.tick(.04);
assert.equal(game.mode,'over','swept collision catches an obstacle crossing the ship');
game.reset();
game.obstacles.push({x:40, y:750, radius:18, speed:100, angle:0, spin:0});
game.tick(.01);
assert.equal(game.passed,1,'passing an obstacle awards a bonus');
assert.equal(game.obstacles.length,0,'offscreen obstacles are removed');
game.tick(Number.NaN);
assert.ok(Number.isFinite(game.score),'invalid time does not corrupt state');
console.log('PASS: boundaries, spawn, score, pause/resume, restart, swept collision, cleanup.');
